Fix growbuffer_append
This fixes the following error encountered when uploading large files:

ERROR: ErrorMalformedXML
  Message: The XML you provided was not well-formed or did not
  validate against our published schema.

This becomes a problem after a previous patch increases the size limit for a single object, causing more than one growbuffer to be allocated for holding the XML.